---
# tasks file for plusclouds.automation.windows.iis
- name: iis
  win_feature:
    name: "web-server"
    state: present
    restart: yes
    include_sub_features: yes
    include_management_tools: yes

- name: Reboot if installing Web-Server feature requires it
  win_reboot:
  when: win_feature.reboot_required