- name: AD windows
  hosts: win
  gather_facts: no
  tasks:
  - name: Install AD Services feature
    win_feature:
      name: AD-Domain-Services
      include_management_tools: yes
      include_sub_features: yes
      state: present
