  
- name: license deneme
  hosts: win
  gather_facts: no
  tasks:
    - name: Get product id and product key
      win_product_facts:

    - name: Display Windows edition
      debug:
        var: ansible_os_license_edition

    - name: Display Windows license status
      debug:
        var: ansible_os_license_status
