- name: special for master1 &&Stop master1
  mysql_replication:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    mode: stopslave

- name: special for master1 && set up the master1 
  mysql_replication:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    mode: changemaster
    master_host: "{{ hostvars['master2']['ansible_host'] }}"
    master_user: "replica"
    master_password: "password"
    master_log_file: "{{hostvars['master2']['master2'].File}}"
    master_log_pos: "{{hostvars['master2']['master2'].Position}}"
  
- name: Start slave
  mysql_replication:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    mode: startslave
