- name: special for master2 &&Stop master2
  mysql_replication:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    mode: stopslave

- name: special for master2 && set up the master2 
  mysql_replication:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    mode: changemaster
    master_host: "{{ hostvars['master1']['ansible_host'] }}"
    master_user: "replica"
    master_password: "password"
    master_log_file: "{{hostvars['master1']['master1'].File}}"
    master_log_pos: "{{hostvars['master1']['master1'].Position}}"
  
- name: Start slave
  mysql_replication:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    mode: startslave
