
- name: check downloaded file exists
  win_stat:
    path: c:\sql{{ install_version }}\sql_installer.exe
  register: installer_file
- name: get the installer
  win_get_url:
    url: "{{ install_url }}"
    dest: 'c:\sql{{ install_version }}\sql_installer.exe'
  when: not installer_file.stat.exists