- name: zabbix
  hosts: zabbix
  remote_user: root
  become: yes
  gather_facts: yes
  tasks:
    - name: send conf zpac.conf
      template:
        src: zcat.sh
        dest: /tmp/zcat.sh

    - name: zcat passwd
      expect:
         command: bash /tmp/zcat.sh
         responses:
           "Enter password": 'password'

    - name: send conf zabbix_server.conf
      template:
        src: /root/ansible/zabbix/zabbix_server.conf
        dest: /etc/zabbix/zabbix_server.conf

    - name: send conf apache.conf
      template:
        src: /root/ansible/zabbix/apache.conf
        dest: /etc/zabbix/apache.conf


    - name: restart mysql Service
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - 'zabbix-server'
        - 'zabbix-agent'
        - 'apache2'

#    - name: enable mysql Service
#      service:
#        name: "{{ item }}"
#        state: enabled
#      with_items:
#        - 'zabbix-server'
#        - 'zabbix-agent'
#        - 'apache2'

    - name: restart enable Service
      command: systemctl enable zabbix-server zabbix-agent apache2
