- name: Windows Roles
  hosts: win
  gather_facts: no
  roles:
    - plusclouds.automation.windows.update
    #- plusclouds.automation.windows.dotnet
    #- plusclouds.automation.windows.iis
    #- plusclouds.automation.windows.active_directory
    #- plusclouds.automation.windows.disk_extansion
    #- plusclouds.automation.windows.add_user        
    #- plusclouds.automation.windows.remove_user
  
  vars:
    - category_names: [ SecurityUpdates , CriticalUpdates, UpdateRollups, Updates ]
    - name: "ozzy"
    - password: "ozzy!"
    - groups: [ Administrators , Users ]