 - name: send conf slave
   template:
     src: /root/ansible/master-slave/50-server.j2
     dest: /etc/mysql/mariadb.conf.d/50-server.cnf
   when: inventory_hostname == 'master'
   vars:
     - bind_address : "{{ hostvars['master']['ansible_host'] }}"
     - server_id : 1

 - name: send conf slave1
   template:
     src: /root/ansible/master-slave/50-server.j2
     dest: /etc/mysql/mariadb.conf.d/50-server.cnf
   when: inventory_hostname != 'master'
   vars:
     - bind_address : "{{ hostvars[inventory_hostname]['ansible_host'] }}"
     - server_id : "{{ hostvars[inventory_hostname]['slave_id'] }}"        
