- name: copy database.sql
  expect:
     command: scp root@"{{ hostvars['master']['ansible_host'] }}":/tmp/database.sql /tmp/
     echo: yes
     responses:
        'password': "{{ hostvars['master']['ansible_ssh_pass'] }}"
        'you want to continue' : 'yes'

- name: Import the database
  mysql_db:
     login_unix_socket: /var/run/mysqld/mysqld.sock
     state: import
     name: all
     target: /tmp/database.sql
