- name: special for server1 && grant slave priv
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: replica
    login_host: "{{ item }}"
    host: "{{ item }}"
    password: "password"
    priv: '*.*:ALL,GRANT'
    state: present
  with_items:
    - "{{ slave_list }} "

- name: special for server1 && show status and register
  mysql_replication:
    mode: getmaster
    login_unix_socket: /var/run/mysqld/mysqld.sock
  register: master

