
- name: special for server2 &&Stop slave
  mysql_replication:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    mode: stopslave

- name: special for server2 && set up the slave 
  mysql_replication:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    mode: changemaster
    master_host: "{{ hostvars['master']['ansible_host'] }}"
    master_user: "replica"
    master_password: "password"
    master_log_file: "{{hostvars['master']['master'].File}}"
    master_log_pos: "{{hostvars['master']['master'].Position}}"
  
- name: Start slave
  mysql_replication:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    mode: startslave

