- name: Check for current Microsoft .NET Framework 4 version
  win_reg_stat:
    path: HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full
    name: Version
  register: dotnet_version

- name: Install Microsoft .NET Framework if version is installable
  include: caller.yaml
  when: dotnet_version.value < install_version

- name: Reboot as required by Microsoft .NET Framework installer
  win_reboot: