
- name: update
  apt:
    update_cache: true

- name: Upgrade pip to be able to install pymysql
  pip:
     name: pip
     extra_args: --upgrade

   
- name: Install pip PyMySQL package
  pip:
     name: PyMySQL
- name: Remove old dumps
  shell: echo ""> /tmp/database.sql

- name: Ansible apt with_items 
  apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
    - 'mysql-server'
    - 'mysql-client'
