- name: special for server1 && grant slave priv
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: replica
    login_host: "{{ hostvars['master2']['ansible_host'] }}"
    host: "{{ hostvars['master2']['ansible_host'] }}"
    password: "password"
    priv: '*.*:ALL,GRANT'
    state: present

- name: Create a new database with name ozzy
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "ozzy1998"
    state: present

#- name: Select query to test_db with named_args
#  mysql: use ozzy1998

#- name: flush tables
#  mysql: flush tables with read lock

- name: special for server1 && show status and register
  mysql_replication:
    mode: getmaster
    login_unix_socket: /var/run/mysqld/mysqld.sock
  register: master1

- name: Dump all databases to database.sql
  mysql_db:
     login_unix_socket: /var/run/mysqld/mysqld.sock
     state: dump
     name: all
     target: /tmp/database.sql


#- name: unlock tables
#  mysql: unlock tables
